filebeat.inputs:
  - type: container
    paths:
      - /var/lib/docker/containers/*/*.log
    processors:
      - add_docker_metadata: ~
    # Opcjonalnie: ogranicz do Twoich usług (lepsza czytelność w Kibanie)
    include_lines: ['api-service', 'external-service']

output.logstash:
  hosts: ["logstash:5044"]

setup.ilm.enabled: false
setup.template.enabled: false
logging.level: info
