spring.application.name=api-service
external.base-url=https://demo-b.gruzewski.dev

management.endpoints.web.exposure.include=health,prometheus
management.prometheus.metrics.export.enabled=true
management.metrics.distribution.percentiles-histogram.http.server.requests=true
management.observations.http.server.requests.enabled=true
